{
    "repository": "developmentseed/geojson-pydantic",
    "stars": 141,
    "language": "python",
    "size": 184,
    "clone_url": "https://github.com/developmentseed/geojson-pydantic.git",
    "timestamp": "2023-07-01T14:58:44.926786Z",
    "clone_success": true,
    "number_of_actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_build_tools": [
        "pytest"
    ],
    "actions_test_build_tools": [
        "pytest"
    ],
    "actions_run": {
        "failed": true,
        "tests": [
            {
                "classname": "",
                "name": "tests.test_features",
                "time": 0.0,
                "results": [
                    {
                        "result": "Error",
                        "message": "collection failure",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "",
                "name": "tests.test_geometries",
                "time": 0.0,
                "results": [
                    {
                        "result": "Error",
                        "message": "collection failure",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "",
                "name": "tests.test_package",
                "time": 0.0,
                "results": [
                    {
                        "result": "Error",
                        "message": "collection failure",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            }
        ],
        "stdout": "[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \ud83d\ude80  Start image=crawlergpt:latest\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic] user=0 workdir=\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2601  git clone 'https://github.com/codecov/codecov-action' # ref=v1\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \ud83e\uddea  Matrix: map[python-version:3.8]\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \u2b50 Run Main actions/checkout@v3\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2705  Success - Main actions/checkout@v3\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \u2b50 Run Main Set up Python 3.8\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker cp src=/tmp/act-cache/c44f90b7-3a51-41a9-8498-c8c1e19edb50/act/actions-setup-python@v4/ dst=/var/run/act/actions/actions-setup-python@v4/\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/actions-setup-python@v4/] user=0 workdir=\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v4/dist/setup/index.js] user= workdir=\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::Python is expected to be installed into /opt/hostedtoolcache\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2753  ::group::Installed versions\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::Semantic version spec of 3.8 is 3.8\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: \n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? false\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? true\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? true\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? true\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? true\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? true\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::explicit? true\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::evaluating 6 versions\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::matched: 3.8.11\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.8.11/x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udcac  ::debug::Found tool in cache Python 3.8.11 x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Successfully set up CPython (3.8.11)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2753  ::endgroup::\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2753 add-matcher /run/act/actions/actions-setup-python@v4/.github/python.json\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2705  Success - Main Set up Python 3.8\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-env:: PKG_CONFIG_PATH=/opt/hostedtoolcache/Python/3.8.11/x64/lib/pkgconfig\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-env:: Python_ROOT_DIR=/opt/hostedtoolcache/Python/3.8.11/x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-env:: Python2_ROOT_DIR=/opt/hostedtoolcache/Python/3.8.11/x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-env:: Python3_ROOT_DIR=/opt/hostedtoolcache/Python/3.8.11/x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.8.11/x64/lib\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.8.11/x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-output:: python-version=3.8.11\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::set-output:: python-path=/opt/hostedtoolcache/Python/3.8.11/x64/bin/python\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.8.11/x64\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.8.11/x64/bin\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \u2b50 Run Main Install dependencies\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (21.2.4)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting pip\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Installing collected packages: pip\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Attempting uninstall: pip\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     Found existing installation: pip 21.2.4\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     Uninstalling pip-21.2.4:\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |       Successfully uninstalled pip-21.2.4\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Successfully installed pip-23.1.2\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Processing /tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Installing build dependencies: started\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Installing build dependencies: finished with status 'done'\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Getting requirements to build wheel: started\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Getting requirements to build wheel: finished with status 'done'\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Preparing metadata (pyproject.toml): started\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Preparing metadata (pyproject.toml): finished with status 'done'\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting pydantic (from geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading pydantic-2.0-py3-none-any.whl (355 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 355.6/355.6 kB 1.4 MB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting pytest (from geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading pytest-7.4.0-py3-none-any.whl (323 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 323.6/323.6 kB 3.8 MB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting pytest-cov (from geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading pytest_cov-4.1.0-py3-none-any.whl (21 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting shapely (from geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading shapely-2.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 2.3/2.3 MB 35.5 MB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting annotated-types>=0.4.0 (from pydantic->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading annotated_types-0.5.0-py3-none-any.whl (11 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting pydantic-core==2.0.1 (from pydantic->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading pydantic_core-2.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 1.5/1.5 MB 12.5 MB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting typing-extensions>=4.6.1 (from pydantic->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading typing_extensions-4.7.0-py3-none-any.whl (33 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting iniconfig (from pytest->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting packaging (from pytest->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading packaging-23.1-py3-none-any.whl (48 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 48.9/48.9 kB 616.0 kB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting pluggy<2.0,>=0.12 (from pytest->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading pluggy-1.2.0-py3-none-any.whl (17 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting exceptiongroup>=1.0.0rc8 (from pytest->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting tomli>=1.0.0 (from pytest->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting coverage[toml]>=5.2.1 (from pytest-cov->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading coverage-7.2.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (229 kB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 229.9/229.9 kB 1.6 MB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Collecting numpy>=1.14 (from shapely->geojson-pydantic==0.6.2)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 17.3/17.3 MB 17.6 MB/s eta 0:00:00\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Building wheels for collected packages: geojson-pydantic\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Building wheel for geojson-pydantic (pyproject.toml): started\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Building wheel for geojson-pydantic (pyproject.toml): finished with status 'done'\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Created wheel for geojson-pydantic: filename=geojson_pydantic-0.6.2-py3-none-any.whl size=9781 sha256=5bacaf8b902ccaaaca68195fb9154b71b275856d51c199a4644a39cbb9a718f4\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |   Stored in directory: /home/runneradmin/.cache/pip/wheels/67/36/dc/04e16f0bc084ff370286fa5fcc60e995e62a1fa4c014ff6fea\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Successfully built geojson-pydantic\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Installing collected packages: typing-extensions, tomli, pluggy, packaging, numpy, iniconfig, exceptiongroup, coverage, shapely, pytest, pydantic-core, annotated-types, pytest-cov, pydantic, geojson-pydantic\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Successfully installed annotated-types-0.5.0 coverage-7.2.7 exceptiongroup-1.1.1 geojson-pydantic-0.6.2 iniconfig-2.0.0 numpy-1.24.4 packaging-23.1 pluggy-1.2.0 pydantic-2.0 pydantic-core-2.0.1 pytest-7.4.0 pytest-cov-4.1.0 shapely-2.0.1 tomli-2.0.1 typing-extensions-4.7.0\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | \n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | [notice] A new release of pip is available: 21.1.1 -> 23.1.2\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | [notice] To update, run: pip install --upgrade pip\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u2705  Success - Main Install dependencies\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \u2b50 Run Main Run tests\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ============================= test session starts ==============================\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | platform linux -- Python 3.8.11, pytest-7.4.0, pluggy-1.2.0\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | rootdir: /tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | plugins: cov-4.1.0\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | collected 0 items / 3 errors\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | \n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ==================================== ERRORS ====================================\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ___________________ ERROR collecting tests/test_features.py ____________________\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ImportError while importing test module '/tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic/tests/test_features.py'.\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Hint: make sure your test modules/packages have valid Python names.\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Traceback:\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/importlib/__init__.py:127: in import_module\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     return _bootstrap._gcd_import(name[level:], package, level)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | tests/test_features.py:8: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from geojson_pydantic.features import Feature, FeatureCollection\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/__init__.py:3: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from .features import Feature, FeatureCollection  # noqa\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/features.py:6: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from pydantic.generics import GenericModel\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | E   ImportError: cannot import name 'GenericModel' from 'pydantic.generics' (/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pydantic/generics.py)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | __________________ ERROR collecting tests/test_geometries.py ___________________\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ImportError while importing test module '/tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic/tests/test_geometries.py'.\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Hint: make sure your test modules/packages have valid Python names.\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Traceback:\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/importlib/__init__.py:127: in import_module\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     return _bootstrap._gcd_import(name[level:], package, level)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | tests/test_geometries.py:8: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from geojson_pydantic.geometries import (\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/__init__.py:3: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from .features import Feature, FeatureCollection  # noqa\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/features.py:6: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from pydantic.generics import GenericModel\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | E   ImportError: cannot import name 'GenericModel' from 'pydantic.generics' (/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pydantic/generics.py)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ____________________ ERROR collecting tests/test_package.py ____________________\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ImportError while importing test module '/tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic/tests/test_package.py'.\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Hint: make sure your test modules/packages have valid Python names.\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Traceback:\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/importlib/__init__.py:127: in import_module\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     return _bootstrap._gcd_import(name[level:], package, level)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | tests/test_package.py:1: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     import geojson_pydantic\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/__init__.py:3: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from .features import Feature, FeatureCollection  # noqa\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/features.py:6: in <module>\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   |     from pydantic.generics import GenericModel\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | E   ImportError: cannot import name 'GenericModel' from 'pydantic.generics' (/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pydantic/generics.py)\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | - generated xml file: /tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic/report.xml -\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | \n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ---------- coverage: platform linux, python 3.8.11-final-0 -----------\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Name                                Stmts   Miss Branch BrPart  Cover   Missing\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | -------------------------------------------------------------------------------\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/__init__.py            4      3      0      0    25%   4-16\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/features.py           31     28      2      0     9%   8-55\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/geo_interface.py       8      8      0      0     0%   3-23\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/geometries.py        156    156     50      0     0%   2-337\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | geojson_pydantic/types.py              25     25     10      0     0%   3-57\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | -------------------------------------------------------------------------------\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | TOTAL                                 224    220     62      0     1%\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | Coverage XML written to file coverage.xml\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | \n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | =========================== short test summary info ============================\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ERROR tests/test_features.py\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ERROR tests/test_geometries.py\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ERROR tests/test_package.py\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | !!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   | ============================== 3 errors in 1.31s ===============================\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests]   \u274c  Failure - Main Run tests\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] exitcode '2': failure\n[1118322d-118e-44e6-8f29-36c36fa6f564/tests] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'tests' failed\n",
        "workflow": {
            "path": "/tmp/558156d8-17ed-11ee-8a50-bb14de238602/developmentseed-geojson-pydantic/.github/workflows/ci-crawler.yml",
            "type": "pytest"
        },
        "workflow_name": "1118322d-118e-44e6-8f29-36c36fa6f564",
        "build_tool": "pytest",
        "elapsed_time": 218.41972279548645
    }
}