{
    "repository": "dolthub/doltpy",
    "stars": 53,
    "language": "python",
    "size": 2203,
    "clone_url": "https://github.com/dolthub/doltpy.git",
    "timestamp": "2023-07-01T13:52:41.430658Z",
    "clone_success": true,
    "number_of_actions": 3,
    "number_of_test_actions": 1,
    "actions_successful": true,
    "actions_build_tools": [
        "unknown",
        "unknown",
        "pytest"
    ],
    "actions_test_build_tools": [
        "pytest"
    ],
    "actions_run": {
        "failed": false,
        "tests": [
            {
                "classname": "tests.cli.test_read",
                "name": "test_read_pandas_csv",
                "time": 3.325,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.cli.test_read",
                "name": "test_read_pandas_pq",
                "time": 3.382,
                "results": [
                    {
                        "result": "Failure",
                        "message": "TypeError: __init__() got an unexpected keyword argument 'remote'",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.cli.test_write",
                "name": "test_write_pandas",
                "time": 0.804,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.cli.test_write",
                "name": "test_write_pandas_accept_nulls_on_update",
                "time": 0.947,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_dataframe_table_loader_create",
                "time": 0.356,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_dataframe_table_loader_update",
                "time": 0.425,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_table_transformer_create",
                "time": 0.29,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_table_transformer_update",
                "time": 0.367,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_insert_unique_key",
                "time": 0.367,
                "results": [
                    {
                        "result": "Failure",
                        "message": "TypeError: __init__() got an unexpected keyword argument 'remote'",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_insert_unique_key_column_error",
                "time": 0.004,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_get_unique_key_update_writer",
                "time": 0.291,
                "results": [
                    {
                        "result": "Failure",
                        "message": "TypeError: __init__() got an unexpected keyword argument 'remote'",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_branching",
                "time": 0.335,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_get_bulk_table_loader",
                "time": 0.909,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_load_to_dolt_new_branch",
                "time": 0.308,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_multi_branch_load",
                "time": 0.327,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.etl.test_tools",
                "name": "test_branch_creator",
                "time": 0.269,
                "results": [
                    {
                        "result": "Error",
                        "message": "failed on setup with \"TypeError: __init__() got an unexpected keyword argument 'remote'\"",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_read",
                "name": "test_read_rows",
                "time": 3.246,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_read",
                "name": "test_read_columns",
                "time": 2.919,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_read",
                "name": "test_read_pandas",
                "time": 3.401,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_sql",
                "name": "test_context_manager_cleanup",
                "time": 2.603,
                "results": [
                    {
                        "result": "Failure",
                        "message": "AssertionError: assert 0 >= 1\n +  where 0 = _count_proc_helper('zombie')",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_sql",
                "name": "test_commit_tables",
                "time": 4.387,
                "results": [
                    {
                        "result": "Failure",
                        "message": "doltcli.dolt.DoltException: (\"sql --query select HASHOF('HEAD') as hash --result-format csv\", '', 'You\\'ve encountered a new behavior in dolt which is not fully documented yet.\\nA local dolt server is using your dolt data directory, and in an attempt to service your request, we are attempting to \\nconnect to it. That has failed. You should stop the server, or reach out to @macneale on https://discord.gg/gqr7K4VNKe\\nfor help.\\nA local server is running, and dolt is failing to connect. Error connecting to remote database: \"error on line 1 for query select HASHOF(\\'HEAD\\') as hash: dial tcp 127.0.0.1:3306: connect: connection refused\".\\n\\n', 1)",
                        "type": null
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_sql",
                "name": "test_commit_tables_empty_commit",
                "time": 0.001,
                "results": [
                    {
                        "result": "Skipped",
                        "message": "unconditional skip",
                        "type": "pytest.skip"
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_sql",
                "name": "test_show_tables",
                "time": 4.67,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_sql",
                "name": "test_show_tables_engine",
                "time": 1.26,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_sql",
                "name": "test_log_file",
                "time": 2.016,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_write",
                "name": "test_write_columns",
                "time": 3.519,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_write",
                "name": "test_write_rows",
                "time": 3.398,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_write",
                "name": "test_write_pandas_update",
                "time": 3.341,
                "results": [
                    {
                        "result": "Passed",
                        "message": "",
                        "type": ""
                    }
                ],
                "stdout": null,
                "stderr": null
            },
            {
                "classname": "tests.sql.test_write",
                "name": "test_write_file",
                "time": 0.003,
                "results": [
                    {
                        "result": "Skipped",
                        "message": "unconditional skip",
                        "type": "pytest.skip"
                    }
                ],
                "stdout": null,
                "stderr": null
            }
        ],
        "stdout": "[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \ud83d\ude80  Start image=crawlergpt:latest\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/dolthub-doltpy] user=0 workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2601  git clone 'https://github.com/Gr1N/setup-poetry' # ref=v8\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2601  git clone 'https://github.com/actions/cache' # ref=v1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2601  git clone 'https://github.com/codecov/codecov-action' # ref=v1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \ud83e\uddea  Matrix: map[python-version:3.7]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main actions/checkout@v2\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main actions/checkout@v2\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Set up Python 3.7\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker cp src=/tmp/act-cache/2cfe23c5-504e-46ff-ba2e-6f0b44c256ba/act/actions-setup-python@v1/ dst=/var/run/act/actions/actions-setup-python@v1/\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/actions-setup-python@v1/] user=0 workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v1/dist/index.js] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Semantic version spec of 3.7 is 3.7\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? false\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? true\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? true\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? true\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? true\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? true\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::explicit? true\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::evaluating 6 versions\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::matched: 3.7.11\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.7.11/x64\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Found tool in cache Python 3.7.11 x64\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Successfully setup CPython (3.7.11)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2753 add-matcher /run/act/actions/actions-setup-python@v1/.github/python.json\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main Set up Python 3.7\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.7.11/x64\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2699  ::set-output:: python-version=3.7.11\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64/bin\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Install dependencies\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                                  Dload  Upload   Total   Spent    Left  Speed\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \r100  3167  100  3167    0     0   3574      0 --:--:-- --:--:-- --:--:--  3574\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Downloading: https://github.com/dolthub/dolt/releases/download/v1.7.2/dolt-linux-amd64.tar.gz\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing dolt /usr/local/bin.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Config successfully updated.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Config successfully updated.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Config successfully updated.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Config successfully updated.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main Install dependencies\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Gr1N/setup-poetry@v8\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker cp src=/tmp/act-cache/2cfe23c5-504e-46ff-ba2e-6f0b44c256ba/act/Gr1N-setup-poetry@v8/ dst=/var/run/act/actions/Gr1N-setup-poetry@v8/\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/Gr1N-setup-poetry@v8/] user=0 workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/Gr1N-setup-poetry@v8/dist/index.js] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Downloading https://install.python-poetry.org\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Destination /tmp/47f41854-fccd-4b16-86ee-e13f0326f0ed\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::download complete\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | [command]/opt/hostedtoolcache/Python/3.7.11/x64/bin/python /tmp/47f41854-fccd-4b16-86ee-e13f0326f0ed --yes\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Retrieving Poetry metadata\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | # Welcome to Poetry!\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | This will download and install the latest version of Poetry,\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | a dependency and package manager for Python.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | It will add the `poetry` command to Poetry's bin directory, located at:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.local/bin\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | You can uninstall at any time by executing this script with the --uninstall option,\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | and these changes will be reverted.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing Poetry (1.5.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing Poetry (1.5.1): Creating environment\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing Poetry (1.5.1): Installing Poetry\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing Poetry (1.5.1): Creating script\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing Poetry (1.5.1): Done\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Poetry (1.5.1) is installed now. Great!\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | To get started you need Poetry's bin directory (/home/runneradmin/.local/bin) in your `PATH`\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | environment variable.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Add `export PATH=\"/home/runneradmin/.local/bin:$PATH\"` to your shell configuration file.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Alternatively, you can call Poetry explicitly with `/home/runneradmin/.local/bin/poetry`.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | You can test that everything is set up by executing:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | `poetry --version`\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main Gr1N/setup-poetry@v8\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2699  ::add-path:: /home/runneradmin/.local/bin\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main actions/cache@v1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker cp src=/tmp/act-cache/2cfe23c5-504e-46ff-ba2e-6f0b44c256ba/act/actions-cache@v1/ dst=/var/run/act/actions/actions-cache@v1/\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/actions-cache@v1/] user=0 workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-cache@v1/dist/restore/index.js] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Cache Path: /home/runneradmin/.cache/pypoetry/virtualenvs\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Resolved Keys:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::[\"Linux-3.7-poetry-79fceef14a7993741289a56f22c98c4b8605e0e97762403d94ecfba75872700e\",\"Linux-3.7-poetry-\"]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:37829/_apis/artifactcache/cache?keys=Linux-3.7-poetry-79fceef14a7993741289a56f22c98c4b8605e0e97762403d94ecfba75872700e%252CLinux-3.7-poetry-\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Cache not found for input keys: Linux-3.7-poetry-79fceef14a7993741289a56f22c98c4b8605e0e97762403d94ecfba75872700e, Linux-3.7-poetry-.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main actions/cache@v1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Install poetry dependencies\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Creating virtualenv doltpy-QlWai6Ur-py3.7 in /home/runneradmin/.cache/pypoetry/virtualenvs\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing dependencies from lock file\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Package operations: 72 installs, 0 updates, 0 removals\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pycparser (2.21)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing cffi (1.15.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing bcrypt (3.2.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing certifi (2022.5.18.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing charset-normalizer (2.0.12)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing cryptography (37.0.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing idna (3.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pynacl (1.5.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing six (1.15.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing typing-extensions (4.1.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing urllib3 (1.26.9)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing zipp (3.6.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing attrs (19.3.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing importlib-metadata (4.8.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing paramiko (2.11.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pyparsing (2.4.7)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pyrsistent (0.18.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing requests (2.27.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing websocket-client (0.59.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing cached-property (1.5.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing distlib (0.3.4)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing distro (1.7.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing docker (5.0.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing dockerpty (0.4.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing docopt (0.6.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing filelock (3.4.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing iniconfig (1.1.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing jsonschema (3.2.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing packaging (20.4)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing platformdirs (2.4.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pluggy (0.13.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing py (1.11.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing python-dotenv (0.20.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pyyaml (5.4.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing texttable (1.6.4)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing toml (0.10.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing appdirs (1.4.4)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing argcomplete (1.12.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing click (8.0.4)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing colorlog (4.8.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing coverage (6.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing decorator (4.4.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing docker-compose (1.29.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing mypy-extensions (0.4.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing numpy (1.19.5)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pathspec (0.9.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing protobuf (3.12.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pytest (6.2.5)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing python-dateutil (2.8.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pytz (2021.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing regex (2022.4.24)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing sortedcontainers (2.4.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing typed-ast (1.4.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing virtualenv (20.14.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing black (20.8b1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing cx-oracle (8.3.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing doltcli (0.1.15)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing hypothesis (6.31.6)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing isort (5.10.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing more-itertools (8.13.0)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing mypy (0.800)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing mysql-connector-python (8.0.20)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing nox (2020.12.31)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pandas (1.1.5)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing psutil (5.7.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing psycopg2-binary (2.8.5)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pyarrow (6.0.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pytest-cov (2.12.1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing pytest-docker (0.10.3)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing retry (0.9.2)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing sqlalchemy (1.3.18)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   \u2022 Installing wcwidth (0.2.5)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Connection pool is full, discarding connection: pypi.org. Connection pool size: 10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Installing the current project: doltpy (2.0.14)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main Install poetry dependencies\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Execute black\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/6] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | All done! \u2728 \ud83c\udf70 \u2728\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | 25 files would be left unchanged.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main Execute black\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Execute mypy\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/7] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Success: no issues found in 23 source files\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u2705  Success - Main Execute mypy\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \u2b50 Run Main Execute pytest\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/8] user= workdir=\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ============================= test session starts ==============================\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | platform linux -- Python 3.7.11, pytest-6.2.5, py-1.11.0, pluggy-0.13.1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | rootdir: /tmp/558156d8-17ed-11ee-8a50-bb14de238602/dolthub-doltpy, configfile: pyproject.toml\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | plugins: cov-2.12.1, docker-0.10.3, hypothesis-6.31.6\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | collected 29 items\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_read.py .F                                                [  6%]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_write.py ..                                               [ 13%]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py EEEEF.FE.EEE                                     [ 55%]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/sql/test_read.py ...                                               [ 65%]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/sql/test_sql.py FFs...                                             [ 86%]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/sql/test_write.py ...s                                             [100%]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ==================================== ERRORS ====================================\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _____________ ERROR at setup of test_dataframe_table_loader_create _____________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_dataframe_table_loader_cr0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f683e17f290>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _____________ ERROR at setup of test_dataframe_table_loader_update _____________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_dataframe_table_loader_up0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f683e17f3d0>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _______________ ERROR at setup of test_table_transformer_create ________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_table_transformer_create0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f68251d2610>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _______________ ERROR at setup of test_table_transformer_update ________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_table_transformer_update0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f684f4cd910>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _______________________ ERROR at setup of test_branching _______________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_branching0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f68251f7150>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ________________ ERROR at setup of test_load_to_dolt_new_branch ________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_load_to_dolt_new_branch0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f682520fe50>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ___________________ ERROR at setup of test_multi_branch_load ___________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_multi_branch_load0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f68251f58d0>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ____________________ ERROR at setup of test_branch_creator _____________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_branch_creator0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     @pytest.fixture\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def initial_test_data(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       return _populate_test_data_helper(init_empty_test_repo, INITIAL_MENS, INITIAL_WOMENS)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:44: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:32: in _populate_test_data_helper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branch=branch)(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f683e19aa50>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | =================================== FAILURES ===================================\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _____________________________ test_read_pandas_pq ______________________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | with_initial_test_data = (Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_read_pandas_pq0'), print_output=False), 'qkb69b43npkicd7vcm8i86d9i0k8boce')\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def test_read_pandas_pq(with_initial_test_data):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         dolt, first_commit = with_initial_test_data\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         second_commit = update_test_data(dolt)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       first_write = read_pandas(dolt, TEST_TABLE, first_commit, fmt=\"parquet\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_read.py:52: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/cli/read.py:59: in read_pandas\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return read_pandas_parquet(dolt, table, as_of)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/cli/read.py:52: in read_pandas_parquet\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     dolt.branch(tmp_branch, delete=True)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:776: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return execute_wrapper(args)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:755: in execute_wrapper\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f682519ae50>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ____________________________ test_insert_unique_key ____________________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_insert_unique_key0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def test_insert_unique_key(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         repo = init_empty_test_repo\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         def generate_data():\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             return pd.DataFrame({'id': [1, 1, 2], 'value': ['foo', 'foo', 'baz']})\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         test_table = 'test_data'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         get_dolt_loader([get_df_table_writer(test_table, generate_data, ['hash_id'], transformers=[insert_unique_key])],\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                         True,\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >                       'Updating test data')(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:121: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f68251f5a90>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ______________________ test_get_unique_key_update_writer _______________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_get_unique_key_update_wri0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def test_get_unique_key_update_writer(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         repo = init_empty_test_repo\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         def generate_initial_data():\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             return pd.DataFrame([\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                 {'name': 'Roger', 'id': 1},\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                 {'name': 'Rafael', 'id': 2},\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                 {'name': 'Rafael', 'id': 2},\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                 {'name': 'Novak', 'id': 3}\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             ])\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         test_table = 'test_data'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         get_dolt_loader([get_unique_key_table_writer(test_table, generate_initial_data, import_mode='create')],\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                         True,\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >                       'Create test data')(repo)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/etl/test_tools.py:148: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py:252: in inner\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     current_branch, current_branch_list = repo.branch()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:747: in branch\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     return self._get_branches()\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: in _get_branches\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | .0 = <list_iterator object at 0x7f68251d2b50>\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >   branches = [Branch(**d) for d in dicts]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E   TypeError: __init__() got an unexpected keyword argument 'remote'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:797: TypeError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _________________________ test_context_manager_cleanup _________________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | init_empty_test_repo = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_context_manager_cleanup0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def test_context_manager_cleanup(init_empty_test_repo):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         dolt = init_empty_test_repo\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         with DoltSQLServerContext(dolt, TEST_SERVER_CONFIG) as _:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             assert _count_proc_helper('running') + _count_proc_helper('sleeping') >= 1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       assert _count_proc_helper('zombie') >= 1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E       AssertionError: assert 0 >= 1\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E        +  where 0 = _count_proc_helper('zombie')\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/sql/test_sql.py:45: AssertionError\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ------------------------------ Captured log call -------------------------------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | WARNING  retry.api:api.py:40 (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | (Background on this error at: http://sqlalche.me/e/13/4xp6), retrying in 2 seconds...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ______________________________ test_commit_tables ______________________________\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | with_test_tables = Dolt(repo_dir=local('/tmp/pytest-of-runneradmin/pytest-0/test_commit_tables0'), print_output=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def test_commit_tables(with_test_tables):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         dolt = with_test_tables\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         with DoltSQLServerContext(dolt, TEST_SERVER_CONFIG) as dssc:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             dssc.write_rows(TEST_TABLE_ONE, TEST_DATA_INITIAL, commit=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             dssc.write_rows(TEST_TABLE_TWO, TEST_DATA_INITIAL, commit=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             dssc.commit_tables(COMMIT_MESSAGE, [TEST_TABLE_ONE, TEST_TABLE_TWO], False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >       _, commit = dolt.log().popitem(last=False)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/sql/test_sql.py:59: \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:638: in log\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     sql=Commit.get_log_table_query(number=number, commit=commit, head=self.head),\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:283: in head\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     head_commit = self.sql(f\"select {head_hash} as hash\", result_format=\"csv\")[0].get(\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:616: in sql\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     output_file = self.execute(args, stdout_to_file=f, **kwargs)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:332: in execute\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     output = _execute(args, self.repo_dir, outfile=stdout_to_file)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | args = ['sql', '--query', \"select HASHOF('HEAD') as hash\", '--result-format', 'csv']\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | cwd = local('/tmp/pytest-of-runneradmin/pytest-0/test_commit_tables0')\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | outfile = '/tmp/tmpbn4g3ihb/tmpfile'\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     def _execute(args: List[str], cwd: Optional[str] = None, outfile: Optional[str] = None):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         from .utils import DOLT_PATH\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         _args = [DOLT_PATH] + args\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         str_args = \" \".join(\" \".join(args).split())\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         logger.info(str_args)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         if outfile:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             with open(outfile, \"w\", newline=\"\") as f:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |                 proc = Popen(args=_args, cwd=cwd, stdout=f, stderr=PIPE)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         else:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             proc = Popen(args=_args, cwd=cwd, stdout=PIPE, stderr=PIPE)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         out, err = (val.decode(\"utf8\") if val else \"\" for val in proc.communicate())\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         exitcode = proc.returncode\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |         if exitcode != 0:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |             logger.error(err)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | >           raise DoltException(str_args, out, err, exitcode)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | E           doltcli.dolt.DoltException: (\"sql --query select HASHOF('HEAD') as hash --result-format csv\", '', 'You\\'ve encountered a new behavior in dolt which is not fully documented yet.\\nA local dolt server is using your dolt data directory, and in an attempt to service your request, we are attempting to \\nconnect to it. That has failed. You should stop the server, or reach out to @macneale on https://discord.gg/gqr7K4VNKe\\nfor help.\\nA local server is running, and dolt is failing to connect. Error connecting to remote database: \"error on line 1 for query select HASHOF(\\'HEAD\\') as hash: dial tcp 127.0.0.1:3306: connect: connection refused\".\\n\\n', 1)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/doltcli/dolt.py:85: DoltException\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ------------------------------ Captured log setup ------------------------------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | WARNING  doltcli.dolt:dolt.py:622 Must provide a value for result_format to get output back\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | WARNING  doltcli.dolt:dolt.py:622 Must provide a value for result_format to get output back\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ----------------------------- Captured stdout call -----------------------------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | [{'hash': 'nb3p0huoovsoejhrsh86h0bkcvqplm6b'}]\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ------------------------------ Captured log call -------------------------------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | WARNING  retry.api:api.py:40 (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | (Background on this error at: http://sqlalche.me/e/13/4xp6), retrying in 2 seconds...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR    doltcli.dolt:dolt.py:84 You've encountered a new behavior in dolt which is not fully documented yet.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | A local dolt server is using your dolt data directory, and in an attempt to service your request, we are attempting to \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | connect to it. That has failed. You should stop the server, or reach out to @macneale on https://discord.gg/gqr7K4VNKe\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | for help.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | A local server is running, and dolt is failing to connect. Error connecting to remote database: \"error on line 1 for query select HASHOF('HEAD') as hash: dial tcp 127.0.0.1:3306: connect: connection refused\".\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | =============================== warnings summary ===============================\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:10\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _nlv = LooseVersion(_np_version)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:11\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _np_version_under1p16 = _nlv < LooseVersion(\"1.16\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:12\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _np_version_under1p17 = _nlv < LooseVersion(\"1.17\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:13\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _np_version_under1p18 = _nlv < LooseVersion(\"1.18\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:14\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _np_version_under1p19 = _nlv < LooseVersion(\"1.19\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:15\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _np_version_under1p20 = _nlv < LooseVersion(\"1.20\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/setuptools/_distutils/version.py:345\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_read.py::test_read_pandas_pq\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/setuptools/_distutils/version.py:345: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     other = LooseVersion(other)\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/function.py:125\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ../../../home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/function.py:125\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/numpy/function.py:125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     if LooseVersion(_np_version) >= LooseVersion(\"1.17.0\"):\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_read.py::test_read_pandas_pq\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/compat/_optional.py:117: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     if distutils.version.LooseVersion(version) < minimum_version:\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_read.py::test_read_pandas_pq\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | tests/cli/test_read.py::test_read_pandas_pq\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |   /home/runneradmin/.cache/pypoetry/virtualenvs/doltpy-QlWai6Ur-py3.7/lib/python3.7/site-packages/pandas/core/arrays/_arrow_utils.py:9: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   |     _pyarrow_version_ge_015 = LooseVersion(pyarrow.__version__) >= LooseVersion(\"0.15\")\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | -- Docs: https://docs.pytest.org/en/stable/warnings.html\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | - generated xml file: /tmp/558156d8-17ed-11ee-8a50-bb14de238602/dolthub-doltpy/report.xml -\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ---------- coverage: platform linux, python 3.7.11-final-0 -----------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Name                              Stmts   Miss  Cover\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | -----------------------------------------------------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/__init__.py                    4      2    50%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/cli/__init__.py                1      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/cli/dolt.py                    1      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/cli/read.py                   34      1    97%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/cli/write.py                  14      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/__init__.py                2      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/loaders.py               145     91    37%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/etl/wrappers.py               20     12    40%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/shared/__init__.py             2      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/shared/helpers.py             17      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/shared/system_helpers.py      17      8    53%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/__init__.py                3      0   100%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/helpers.py                68     37    46%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sql.py                   240     52    78%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/__init__.py          13     13     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/db_tools.py          64     64     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/dolt.py              91     91     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/mysql.py             17     17     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/oracle.py            47     47     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/postgres.py          16     16     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/sql/sync/sync_tools.py        35     35     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/types/__init__.py              1      1     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | doltpy/types/dolt.py                141    141     0%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | -----------------------------------------------------\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | TOTAL                               993    628    37%\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | Coverage XML written to file coverage.xml\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | \n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | =========================== short test summary info ============================\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | FAILED tests/cli/test_read.py::test_read_pandas_pq - TypeError: __init__() go...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | FAILED tests/etl/test_tools.py::test_insert_unique_key - TypeError: __init__(...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | FAILED tests/etl/test_tools.py::test_get_unique_key_update_writer - TypeError...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | FAILED tests/sql/test_sql.py::test_context_manager_cleanup - AssertionError: ...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | FAILED tests/sql/test_sql.py::test_commit_tables - doltcli.dolt.DoltException...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_dataframe_table_loader_create - TypeError...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_dataframe_table_loader_update - TypeError...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_table_transformer_create - TypeError: __i...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_table_transformer_update - TypeError: __i...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_branching - TypeError: __init__() got an ...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_load_to_dolt_new_branch - TypeError: __in...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_multi_branch_load - TypeError: __init__()...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ERROR tests/etl/test_tools.py::test_branch_creator - TypeError: __init__() go...\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   | ======= 5 failed, 14 passed, 2 skipped, 13 warnings, 8 errors in 51.72s ========\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build]   \u274c  Failure - Main Execute pytest\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] exitcode '1': failure\n[bb1e250c-5b70-4009-a138-ba9e695f34fa/build] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'build' failed\n",
        "workflow": {
            "path": "/tmp/558156d8-17ed-11ee-8a50-bb14de238602/dolthub-doltpy/.github/workflows/build-crawler.yaml",
            "type": "pytest"
        },
        "workflow_name": "bb1e250c-5b70-4009-a138-ba9e695f34fa",
        "build_tool": "pytest",
        "elapsed_time": 451.1444914340973
    }
}