{
    "repository": "galliot-us/smart-social-distancing",
    "stars": 131,
    "language": "python",
    "size": 43734,
    "clone_url": "https://github.com/galliot-us/smart-social-distancing.git",
    "timestamp": "2023-07-01T14:58:49.126001Z",
    "clone_success": true,
    "number_of_actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_build_tools": [
        "pytest"
    ],
    "actions_test_build_tools": [
        "pytest"
    ],
    "actions_run": {
        "failed": true,
        "tests": [],
        "stdout": "[9fee1210-92b3-4407-bd76-184d90e10529/Tests] \ud83d\ude80  Start image=crawlergpt:latest\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/galliot-us-smart-social-distancing] user=0 workdir=\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests] \u2b50 Run Main actions/checkout@v2\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \u2705  Success - Main actions/checkout@v2\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests] \u2b50 Run Main Download docker image\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   | Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=neuralet%2Fsmart-social-distancing&tag=latest-x86_64\": dial unix /var/run/docker.sock: connect: permission denied\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests]   \u274c  Failure - Main Download docker image\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests] exitcode '1': failure\n[9fee1210-92b3-4407-bd76-184d90e10529/Tests] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'Tests' failed\n",
        "workflow": {
            "path": "/tmp/558156d8-17ed-11ee-8a50-bb14de238602/galliot-us-smart-social-distancing/.github/workflows/continuous_integration-crawler.yml",
            "type": "pytest"
        },
        "workflow_name": "9fee1210-92b3-4407-bd76-184d90e10529",
        "build_tool": "pytest",
        "elapsed_time": 78.42730855941772
    }
}