{
    "repository": "smarthomeNG/smarthome",
    "stars": 114,
    "language": "python",
    "size": 133613,
    "clone_url": "https://github.com/smarthomeNG/smarthome.git",
    "timestamp": "2023-07-01T10:47:44.446331Z",
    "clone_success": true,
    "number_of_actions": 5,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_build_tools": [
        "unknown",
        "unknown",
        "unknown",
        "unknown",
        "pytest"
    ],
    "actions_test_build_tools": [
        "pytest"
    ],
    "actions_run": {
        "failed": true,
        "tests": [],
        "stdout": "[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7] \ud83d\ude80  Start image=crawlergpt:latest\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/smarthomeNG-smarthome] user=0 workdir=\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \u2601  git clone 'https://github.com/actions/checkout' # ref=v3\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \u2601  git clone 'https://github.com/actions/checkout' # ref=v3\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \u2601  git clone 'https://github.com/actions/checkout' # ref=v3\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v3\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7] \ud83e\uddea  Matrix: map[python-version:3.7]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7] \u2b50 Run Main Setup OS (Ubuntu)\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/0] user= workdir=\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Hit:1 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Ign:3 https://dl.hhvm.com/ubuntu focal InRelease\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:4 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3622 B]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:5 http://dl.google.com/linux/chrome/deb stable InRelease [1825 B]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Err:6 https://dl.hhvm.com/ubuntu focal Release\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   |   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 108.157.214.54 443]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:7 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [3611 B]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Hit:8 http://archive.ubuntu.com/ubuntu focal InRelease\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:9 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Hit:10 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb focal InRelease\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:11 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ Packages [81.0 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:12 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Err:5 http://dl.google.com/linux/chrome/deb stable InRelease\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:13 https://packages.microsoft.com/ubuntu/20.04/prod focal/main all Packages [2521 B]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:14 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [211 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:15 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2856 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:16 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [28.5 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:17 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [744 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:18 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1066 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:19 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [764 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:20 http://security.ubuntu.com/ubuntu focal-security/multiverse i386 Packages [8141 B]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:21 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2479 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted i386 Packages [36.9 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:23 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2636 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:24 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [39.5 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:25 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1366 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:26 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3336 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:27 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Get:28 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | Reading package lists...\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | E: The repository 'https://dl.hhvm.com/ubuntu focal Release' no longer has a Release file.\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   | W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7]   \u274c  Failure - Main Setup OS (Ubuntu)\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7] exitcode '100': failure\n[1b17f2f5-8043-47e5-8a97-deeb591cfa3a/Python 3.7] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'Python ${{ matrix.python-version }}' failed\n",
        "workflow": {
            "path": "/tmp/558156d8-17ed-11ee-8a50-bb14de238602/smarthomeNG-smarthome/.github/workflows/unittests-crawler.yml",
            "type": "pytest"
        },
        "workflow_name": "1b17f2f5-8043-47e5-8a97-deeb591cfa3a",
        "build_tool": "pytest",
        "elapsed_time": 140.02410745620728
    }
}