{
    "repository": "Vimjas/vint",
    "clone_url": "https://github.com/Vimjas/vint.git",
    "timestamp": "2023-05-29T15:30:14.733460Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[CI/test] \ud83d\ude80  Start image=crawlergpt:latest\n[CI/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[CI/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[CI/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[CI/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/Vimjas-vint] user=0 workdir=\n[CI/test]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[CI/test] Unable to reset to bd6b4b6205c4dbad673328db7b31b7fab9e241c0: EOF\n[CI/test] failed to remove container: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/cb4139b9be972be34c1877c3564cfda535d7fedeb49211f364b2aa3035d50431?force=1&v=1\": context deadline exceeded\n[CI/test] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: context deadline exceeded (original error: <nil>) (original error: EOF)\n"
}