{
    "repository": "mgedmin/restview",
    "clone_url": "https://github.com/mgedmin/restview.git",
    "timestamp": "2023-05-29T14:45:36.009137Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[build/flake8    ] \ud83d\ude80  Start image=crawlergpt:latest\n[build/Python 3.7] \ud83d\ude80  Start image=crawlergpt:latest\n[build/Python 3.7]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[build/flake8    ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[build/flake8    ] failed to remove container: Error response from daemon: No such container: ca2cad5db3e24f2eb32a9349235532e4727e547e67148df3f9e36dd595b5197e\n[build/Python 3.7]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[build/Python 3.7]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[build/Python 3.7]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/mgedmin-restview] user=0 workdir=\n[build/Python 3.7]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[build/Python 3.7]   \u2601  git clone 'https://github.com/actions/cache' # ref=v2\n[build/Python 3.7] \ud83e\uddea  Matrix: map[python-version:3.7]\n[build/Python 3.7] \u2b50 Run Main Git clone\n[build/Python 3.7]   \u2705  Success - Main Git clone\n[build/Python 3.7] \u2b50 Run Main Set up Python 3.7\n[build/Python 3.7]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[build/Python 3.7]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[build/Python 3.7]   | OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown\r\n[build/Python 3.7]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[build/Python 3.7]   \u274c  Failure - Main Set up Python 3.7\n[build/Python 3.7] Error response from daemon: Could not find the file /var/run/act/workflow/pathcmd.txt in container 785f6a69f48e528a4280efd7eacf788ba11513b00b925ec52e969e314dbbe229\n[build/Python 3.7] failed to remove container: Error response from daemon: No such container: 785f6a69f48e528a4280efd7eacf788ba11513b00b925ec52e969e314dbbe229\n[build/Python 3.7] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error response from daemon: remove act-build-flake8-c2c87415bf4e9c3cf0c9c82f84c4389fd54ed9c1705352d3e81f536bfd8f53dc-env: volume is in use - [ca2cad5db3e24f2eb32a9349235532e4727e547e67148df3f9e36dd595b5197e]\n"
}