{
    "repository": "xepor/xepor",
    "clone_url": "https://github.com/xepor/xepor.git",
    "timestamp": "2023-05-29T16:37:24.846460Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Python CI/build] \ud83d\ude80  Start image=crawlergpt:latest\n[Python CI/build]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Python CI/build]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Python CI/build]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Python CI/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/xepor-xepor] user=0 workdir=\n[Python CI/build]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[Python CI/build] Unable to checkout 75f3110429a8c05be0e1bf360334e4cced2b63fa: invalid checksum\n[Python CI/build] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": "Error: invalid checksum\n"
}